version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: lifeos-db
    environment:
      POSTGRES_USER: lifeos
      POSTGRES_PASSWORD: lifeos
      POSTGRES_DB: lifeos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./backend
    container_name: lifeos-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=postgresql+psycopg2://lifeos:lifeos@db:5432/lifeos
    depends_on:
      - db
  web:
    image: node:20-alpine
    working_dir: /app
    container_name: lifeos-web
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
      - NEXT_TELEMETRY_DISABLED=1
    command: sh -c "npm install && npm run dev"
    depends_on:
      - api
volumes:
  pgdata:

